### ISSUE TITLE
Movement Markers Behind Walls

### ISSUE THREAD

**Issue by 9ryex5** [illandril/FoundryVTT-turn-marker#12] opened 2024-12-06 00:34 UTC
**Is your feature request related to a problem? Please describe.**
The movement markers are shown when the moving token is behind a wall for a player, spoiling that there is an enemy and where it is moving.

**Describe the solution you'd like**
Movement Markers shouldn't be shown in places where the moving token can't be seen. Either because of darkness or because of walls that block vision.

**What system(s) do you want this feature to work with?**
D&D 5E

**What other modules do you use that you want to ensure work well with this feature?**
None that I think will conflict.

**Comment by illandril** [comment] 2024-12-06 17:20
Duplicate of #6

**Closed as not planned by illandril** 2024-12-06 17:20 UTC
Labels: enhancement
